export const CTRADER_CLIENT_ID = "24577_SchocunJTnhFKhrg9eGcpRCoUq5SS1yhzYYUJsDpBGRuY5RDn4"
export const CTRADER_CLIENT_SECRET = "dyqrTIdAGoiacznaeBe8Ux1tOHZJeoeXNcfBwA0qGZjmGpYCLW"

export const CTRADER_AUTH_URL = "https://connect.spotware.com/apps/auth"
export const CTRADER_TOKEN_URL = "https://openapi.ctrader.com/apps/token"

export const CTRADER_WS_DEMO = "wss://demo.ctraderapi.com:5036"
export const CTRADER_WS_LIVE = "wss://live.ctraderapi.com:5036"

// Payload type IDs for JSON protocol
export const PayloadType = {
  HEARTBEAT: 51,
  ERROR_RES: 50,

  OA_APPLICATION_AUTH_REQ: 2100,
  OA_APPLICATION_AUTH_RES: 2101,
  OA_ACCOUNT_AUTH_REQ: 2102,
  OA_ACCOUNT_AUTH_RES: 2103,

  OA_NEW_ORDER_REQ: 2106,
  OA_CANCEL_ORDER_REQ: 2108,
  OA_AMEND_ORDER_REQ: 2109,
  OA_AMEND_POSITION_SLTP_REQ: 2110,
  OA_CLOSE_POSITION_REQ: 2111,

  OA_ASSET_LIST_REQ: 2112,
  OA_ASSET_LIST_RES: 2113,
  OA_SYMBOLS_LIST_REQ: 2114,
  OA_SYMBOLS_LIST_RES: 2115,
  OA_SYMBOL_BY_ID_REQ: 2116,
  OA_SYMBOL_BY_ID_RES: 2117,

  OA_TRADER_REQ: 2121,
  OA_TRADER_RES: 2122,
  OA_TRADER_UPDATE_EVENT: 2123,

  OA_RECONCILE_REQ: 2124,
  OA_RECONCILE_RES: 2125,
  OA_EXECUTION_EVENT: 2126,

  OA_SUBSCRIBE_SPOTS_REQ: 2127,
  OA_SUBSCRIBE_SPOTS_RES: 2128,
  OA_UNSUBSCRIBE_SPOTS_REQ: 2129,
  OA_UNSUBSCRIBE_SPOTS_RES: 2130,
  OA_SPOT_EVENT: 2131,
  OA_ORDER_ERROR_EVENT: 2132,

  OA_DEAL_LIST_REQ: 2133,
  OA_DEAL_LIST_RES: 2134,

  OA_GET_ACCOUNTS_BY_ACCESS_TOKEN_REQ: 2149,
  OA_GET_ACCOUNTS_BY_ACCESS_TOKEN_RES: 2150,

  OA_SYMBOL_CATEGORY_REQ: 2161,
  OA_SYMBOL_CATEGORY_RES: 2162,
} as const
